name: example
description: An example project for soti_schema_plus.
publish_to: none

environment:
  sdk: ^3.7.2

dependencies:
  soti_schema_plus:
    path: ../
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
  json_serializable: ^6.11.0
