name: soti_schema_plus
description: A tool for generating schemas from Dart data classes.
version: 1.2.0
homepage: https://github.com/csells/soti_schema_plus
repository: https://github.com/csells/soti_schema_plus

environment:
  sdk: ^3.7.2

dependencies:
  analyzer: ">=7.5.9 <8.0.0"
  build: ^3.0.0
  source_gen: ^3.0.0
  meta: ^1.10.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  lints: ^6.0.0

dependency_overrides:
  analyzer: 7.7.0 # remove when freezed is updated to use analyzer 8.0.0
  source_gen: 3.1.0 # remove when freezed is updated to use source_gen 4.0.0
  dart_style: 3.0.1 # remove when freezed is updated to use dart_style 4.0.0
