name: soti_schema_plus
description: A tool for generating schemas from Dart data classes.
version: 1.1.0
homepage: https://github.com/csells/soti_schema_plus
repository: https://github.com/csells/soti_schema_plus

environment:
  sdk: ^3.7.2

dependencies:
  analyzer: ^7.5.9
  build: ^3.0.0
  source_gen: ^3.0.0
  meta: ^1.10.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  freezed_annotation: ^3.1.0

dev_dependencies:
  lints: ^6.0.0
