name: soti_schema_plus
description: A tool for generating schemas from Dart data classes.
version: 1.1.0
homepage: https://github.com/csells/soti_schema_plus
repository: https://github.com/csells/soti_schema_plus

environment:
  sdk: ^3.7.2

dependencies:
  analyzer: ^8.1.1
  build: ^3.0.2
  source_gen: ^3.1.0
  meta: ^1.15.0
  json_annotation: ^4.9.0
  collection: ^1.18.0
  freezed_annotation: ^3.0.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  build_runner: ^2.4.6
